name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
    - name: install things and set up
      run: |
        git config --global user.email "ties@stuij.se"
        git config --global user.name "Ties Stuij"
        git fetch --unshallow --tags
    - name: make and push tag
      run: |
        echo blob | tee /dev/stderr | grep -q "bl"
