name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2-beta
    - name: install things and set up
      run: |
        git config --global user.email "ties@stuij.se"
        git config --global user.name "Ties Stuij"
        git fetch --unshallow --tags
    - name: make and push tag
      run: |
        printf -v TAG_NAME 'upstream-rebase-%(%Y-%m-%d)T\n' -1
        git tag $TAG_NAME
        git push origin $TAG_NAME
